# Secret Scanning Configuration
# This file configures GitHub's secret scanning to exclude template files
# and placeholder secrets from being flagged as security issues

paths-ignore:
  # Template files containing placeholder secrets for user guidance
  - 'secrets/**/*.template'
  - 'secrets/initialize-all-secrets.sh'  # Contains template generation with placeholders
  - 'secrets/common/example.yaml.template'
  - 'docs/**/*.md'  # Documentation may contain example secrets
  
# Note: These exclusions are specifically for files containing PLACEHOLDER secrets
# that are prefixed with "Placeholder_" or contain obvious dummy values like "XXXXXX"
# Real secrets should NEVER be committed to the repository