# Use default gitleaks rules 
[extend]
useDefault = true

# Minimal allowlist - only exclude impossible placeholders and known false positives
[allowlist]
description = "Exclude standardized impossible placeholders and legitimate config patterns"
regexes = [
    '''<PLACEHOLDER_.*_IMPOSSIBLE>''',
    '''prohibit-password''',
    '''forced-commands-only''',
    '''age1[a-z0-9]{58}''',
    '''tblack-t14-nixos''',
]
paths = [
    '''.*\.template$''',
    '''secrets/.*INSTRUCTIONS.*''',
    '''claude-runtime/.*\.jsonl$''',
]