# Use default gitleaks rules 
[extend]
useDefault = true

# Global allowlist for false positives
[allowlist]
description = "Ignore false positives in documentation and config files"
paths = [
    '''.*\.md$''',
    '''docs/.*''',
    '''secrets/TEMPLATE-.*''',
    '''secrets/.*INSTRUCTIONS.*''',
    '''.*\.template$''',
    '''.*\.nix$''',
]
regexes = [
    '''prohibit-password''',
    '''forced-commands-only''',
    '''age1[a-z0-9]{58}''',
]