# modules/hosts/pa161878-nixos [N]/pa161878-nixos.nix
# Dendritic host composition for pa161878-nixos (WSL work environment)
#
# This module defines both NixOS system and Home Manager configurations
# following the dendritic pattern. It registers both configurations
# using the flake.lib helpers.
#
# Deploy NixOS: sudo nixos-rebuild switch --flake '.#pa161878-nixos'
# Deploy HM:    home-manager switch --flake '.#tim@pa161878-nixos'
{ config, lib, inputs, ... }:
let
  # SSH public keys (shared across configurations)
  sshKeys = {
    timblaktu = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkVsx3oZrqwkfU6FmhqNEeAGN8dj6lPxNcEwVCmJcQh timblaktu@gmail.com";
  };

  # Common user settings
  username = "tim";
  homeDirectory = "/home/${username}";
in
{
  # === NixOS System Module ===
  flake.modules.nixos.pa161878-nixos = { config, lib, pkgs, ... }: {
    imports = [
      # Hardware configuration (generated by nixos-generate-config)
      ../../../hosts/pa161878-nixos/hardware-config.nix
      # Dendritic system type - provides system-cli layer (includes default and minimal)
      inputs.self.modules.nixos.system-cli
      # Dendritic WSL configuration
      inputs.self.modules.nixos.wsl
    ];

    # System default layer configuration (required by system types)
    systemDefault.userName = username;

    # WSL settings (dendritic module)
    # GPU: NVIDIA RTX 2000 Ada (8GB VRAM) via WSL2 passthrough
    wsl-settings = {
      hostname = "pa161878-nixos";
      defaultUser = username;
      sshPort = 2223;
      userGroups = [ "wheel" "dialout" ];
      sshAuthorizedKeys = [ sshKeys.timblaktu ];
      # Enable CUDA support for GPU passthrough
      cuda.enable = true;
    };

    # User environment managed by standalone Home Manager
    # Deploy with: home-manager switch --flake '.#tim@pa161878-nixos'
  };

  # === Home Manager Module ===
  flake.modules.homeManager."tim@pa161878-nixos" = { config, lib, pkgs, ... }: {
    imports = [
      # Dendritic system type - provides home-default layer (includes home-minimal)
      inputs.self.modules.homeManager.home-default
      # Files module (scripts, utilities, completions)
      inputs.self.modules.homeManager.files
      # Dendritic feature modules
      inputs.self.modules.homeManager.shell
      inputs.self.modules.homeManager.git
      inputs.self.modules.homeManager.tmux
      inputs.self.modules.homeManager.neovim
      inputs.self.modules.homeManager.wsl-home
      inputs.self.modules.homeManager.claude-code
      inputs.self.modules.homeManager.opencode
      inputs.self.modules.homeManager.secrets-management
      inputs.self.modules.homeManager.github-auth
      inputs.self.modules.homeManager.gitlab-auth
      inputs.self.modules.homeManager.development-tools
      inputs.self.modules.homeManager.yazi
      inputs.self.modules.homeManager.shell-utils
      inputs.self.modules.homeManager.terminal
      inputs.self.modules.homeManager.system-tools
      inputs.self.modules.homeManager.esp-idf
      inputs.self.modules.homeManager.onedrive
      inputs.self.modules.homeManager.podman
      inputs.self.modules.homeManager.windows-terminal
      inputs.self.modules.homeManager.git-auth-helpers
    ];

    # Dendritic home-minimal options (required by system types)
    homeMinimal = {
      inherit username homeDirectory;
    };

    # WSL home settings (dendritic module)
    wsl-home-settings = {
      distroName = "nixos";
    };

    # ESP-IDF development environment (WSL host)
    espIdf.enable = true;

    # OneDrive utilities (WSL host)
    oneDriveUtils.enable = true;

    # Unified files module (scripts, utilities)
    homeFiles.enable = true;

    # Container tools (podman-tui, podman-compose)
    programs.podman-tools = {
      enable = true;
      enableCompose = true;
      aliases = {
        docker = "podman";
        d = "podman";
        dc = "podman-compose";
      };
    };

    # Enable tmux auto-reload on home-manager generation change
    programs.tmux.autoReload.enable = true;

    # Secrets management (dendritic module)
    secretsManagement = {
      enable = true;
      rbw.email = "timblaktu@gmail.com";
    };

    # GitHub authentication (dendritic module)
    gitAuth.github = {
      enable = true;
      mode = "bitwarden";
      bitwarden = {
        item = "github.com";
        field = "PAT-timtam2026";
      };
      cli.tokenOverrides.pr = {
        item = "github.com";
        field = "PAT-pubclassic";
      };
    };

    # GitLab authentication (HOST-SPECIFIC - work environment)
    gitAuth.gitlab = {
      enable = true;
      mode = "bitwarden";
      host = "git.panasonic.aero";
      bitwarden = {
        item = "GitLab git.panasonic.aero";
        field = "lord (access token)";
      };
      cli.enable = true;
    };

    # Windows Terminal settings management (HOST-SPECIFIC)
    windowsTerminal = {
      enable = true;
      font = {
        face = "CaskaydiaMono NFM, Noto Color Emoji";
        size = 12;
      };
      keybindings = [
        { id = "Terminal.CopyToClipboard"; keys = "ctrl+shift+c"; }
        { id = "Terminal.PasteFromClipboard"; keys = "ctrl+shift+v"; }
        { id = "Terminal.DuplicatePaneAuto"; keys = "alt+shift+d"; }
        { id = "Terminal.NextTab"; keys = "alt+ctrl+l"; }
        { id = "Terminal.PrevTab"; keys = "alt+ctrl+h"; }
      ];
    };

    # Claude Code configuration (using lib presets + work account)
    programs.claude-code = inputs.self.lib.claudeCode.baseConfig // {
      accounts = inputs.self.lib.claudeCode.personalAccounts
             // inputs.self.lib.claudeCode.workAccount;
      statusline = inputs.self.lib.claudeCode.defaultStatusline;
      mcpServers = inputs.self.lib.claudeCode.defaultMcpServers;
      subAgents.custom = inputs.self.lib.claudeCode.defaultSubAgents;
    };

    # OpenCode configuration (using lib presets + work account)
    programs.opencode = inputs.self.lib.openCode.baseConfig // {
      accounts = inputs.self.lib.openCode.personalAccounts
             // inputs.self.lib.openCode.workAccount;
      provider = inputs.self.lib.openCode.baseConfig.provider
              // inputs.self.lib.openCode.workProvider;
      mcpServers = inputs.self.lib.openCode.defaultMcpServers;
      commands = inputs.self.lib.openCode.defaultCommands;
    };
  };

  # === Configuration Registration ===
  # Note: Registration is done in flake-modules/ files using lib helpers.
  # The host module only defines flake.modules.{nixos,homeManager}.* content.
  # This avoids circular dependencies that occur when trying to both define
  # and register configurations in the same module.
  #
  # Registration happens in:
  # - flake-modules/nixos-configurations.nix (uses lib.mkNixos)
  # - flake-modules/home-configurations.nix (uses lib.mkHomeManager)
}
