# Example Home Manager module
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.custom-tool;
in {
  options.programs.custom-tool = {
    enable = mkEnableOption "custom tool";
    
    package = mkOption {
      type = types.package;
      default = pkgs.hello;  # Example default
      description = "Package to use for this tool";
    };
    
    # Add more options as needed
  };
  
  config = mkIf cfg.enable {
    # Your home-manager configuration for the custom tool here
    home.packages = [ cfg.package ];
    
    # Example configuration file
    home.file.".config/custom-tool/config.yaml".text = ''
      # Generated by Home Manager
      version: 1
      settings:
        enabled: true
    '';
  };
}
