# modules/hosts/potato [N]/potato.nix
# Dendritic host composition for potato (ARM SBC running NixOS)
#
# This module defines both NixOS system and Home Manager configurations
# following the dendritic pattern. This is an ARM single-board computer
# used as a lightweight server.
#
# Deploy NixOS: sudo nixos-rebuild switch --flake '.#potato'
# Deploy HM:    home-manager switch --flake '.#tim@potato'
{ config, lib, inputs, ... }:
let
  # Common user settings
  username = "tim";
  homeDirectory = "/home/${username}";
in
{
  # === NixOS System Module ===
  flake.modules.nixos.potato = { config, lib, pkgs, ... }: {
    imports = [
      # Hardware configuration (generated by nixos-generate-config)
      ../../../hosts/potato/hardware-config.nix
      # Dendritic system type - provides system-default layer (includes minimal)
      # Using system-default (not system-cli) for lightweight ARM SBC
      inputs.self.modules.nixos.system-default
      # SOPS secrets
      inputs.sops-nix.nixosModules.sops
    ];

    # Allow unfree packages
    nixpkgs.config.allowUnfree = lib.mkDefault true;

    # ARM platform
    nixpkgs.hostPlatform = "aarch64-linux";

    # System default layer configuration (required by system types)
    systemDefault = {
      userName = username;
      # GPIO group for ARM SBC hardware access
      userGroups = lib.mkDefault [ "wheel" "networkmanager" "gpio" ];
    };

    # Hostname and networking
    networking = {
      hostName = "potato";
      useNetworkd = lib.mkDefault true;
      firewall.enable = lib.mkDefault true;
    };

    # Boot configuration for ARM
    boot.loader = {
      grub.enable = lib.mkDefault false;
      generic-extlinux-compatible.enable = lib.mkDefault true;
    };

    # SSH service - enable for remote access
    services.openssh = {
      enable = lib.mkDefault true;
      ports = lib.mkDefault [ 22 ];
      settings = {
        PermitRootLogin = lib.mkDefault "no";
        PasswordAuthentication = lib.mkDefault false;
      };
    };

    # User configuration - add home-manager package
    users.users.${username}.packages = lib.mkDefault (with pkgs; [
      inputs.home-manager.packages.${pkgs.system}.default
    ]);

    # Basic system packages for ARM SBC
    environment.systemPackages = with pkgs; [
      vim
      wget
      curl
      git
      htop
      tmux
    ];

    # System state version
    system.stateVersion = "24.11";

    # User environment managed by standalone Home Manager
    # Deploy with: home-manager switch --flake '.#tim@potato'
  };

  # === Home Manager Module ===
  flake.modules.homeManager."tim@potato" = { config, lib, pkgs, ... }: {
    imports = [
      # Dendritic system type - provides home-minimal layer (required first)
      inputs.self.modules.homeManager.home-minimal
      # Legacy base module (will be removed in Phase 6)
      # Provides: disabledModules, detailed program configs (no longer provides username/homeDirectory)
      ../../../home/modules/base.nix
      # Dendritic feature modules
      inputs.self.modules.homeManager.shell
      inputs.self.modules.homeManager.git
      inputs.self.modules.homeManager.tmux
      # Note: No neovim - keeping potato lightweight
      inputs.self.modules.homeManager.claude-code
      # opencode: imported via base.nix (home/modules/opencode.nix) - not dendritic yet
      inputs.self.modules.homeManager.secrets-management
      inputs.self.modules.homeManager.github-auth
      # Note: No wsl-home module - this is bare-metal NixOS, not WSL
    ];

    # Dendritic home-minimal options (required by system types)
    homeMinimal = {
      inherit username homeDirectory;
    };

    # Legacy homeBase options for additional features
    homeBase.environmentVariables = {
      EDITOR = "nvim";
    };

    # Enable tmux auto-reload on home-manager generation change
    programs.tmux.autoReload.enable = true;

    # Secrets management (dendritic module)
    secretsManagement = {
      enable = true;
      rbw.email = "timblaktu@gmail.com";
    };

    # GitHub authentication (dendritic module)
    gitAuth.github = {
      enable = true;
      mode = "bitwarden";
      bitwarden = {
        item = "github.com";
        field = "PAT-timtam2026";
      };
      cli.tokenOverrides.pr = {
        item = "github.com";
        field = "PAT-pubclassic";
      };
    };
  };

  # === Configuration Registration ===
  # Note: Registration is done in flake-modules/ files.
  # The host module only defines flake.modules.{nixos,homeManager}.* content.
  # This avoids circular dependencies that occur when trying to both define
  # and register configurations in the same module.
  #
  # Registration happens in:
  # - flake-modules/nixos-configurations.nix
  # - flake-modules/home-configurations.nix
}
