# modules/hosts/mbp [N]/mbp.nix
# Dendritic host composition for mbp (Intel MacBook Pro running NixOS)
#
# This module defines both NixOS system and Home Manager configurations
# following the dendritic pattern. Unlike WSL hosts, this is a bare-metal
# NixOS installation on Intel Mac hardware.
#
# Deploy NixOS: sudo nixos-rebuild switch --flake '.#mbp'
# Deploy HM:    home-manager switch --flake '.#tim@mbp'
{ config, lib, inputs, ... }:
let
  # Common user settings
  username = "tim";
  homeDirectory = "/home/${username}";
in
{
  # === NixOS System Module ===
  flake.modules.nixos.mbp = { config, lib, pkgs, ... }: {
    imports = [
      # Hardware configuration (generated by nixos-generate-config)
      ./_hardware-config.nix
      # Dendritic system type - provides system-cli layer (includes default and minimal)
      inputs.self.modules.nixos.system-cli
      # SOPS secrets
      inputs.sops-nix.nixosModules.sops
    ];

    # Allow unfree packages
    nixpkgs.config.allowUnfree = lib.mkDefault true;

    # System default layer configuration (required by system types)
    systemDefault = {
      userName = username;
      wheelNeedsPassword = false;
      userGroups = lib.mkDefault [ "wheel" "networkmanager" "audio" "video" ];
      consolePackages = lib.mkDefault (with pkgs; [
        kbd
        terminus_font
        powerline-fonts
      ]);
      additionalPackages = lib.mkDefault (with pkgs; [
        kbd
        terminus_font
        powerline-fonts
      ]);
      extraShellAliases = lib.mkDefault { };
    };

    # CLI layer configuration (required by system-cli)
    systemCli = {
      sshPasswordAuth = lib.mkDefault true;
    };

    # Hostname and networking
    networking = {
      hostName = "mbp";
      useNetworkd = lib.mkDefault true;
      firewall.enable = lib.mkDefault false;
      wireless = {
        enable = lib.mkDefault true;
        networks = {
          "SUMMIT-VIS" = {
            psk = "summ1tv1s1t0r";
          };
          "zarf" = {
            psk = "c0rnp177a";
          };
        };
      };
    };

    systemd.network.enable = lib.mkDefault true;

    # Configure systemd-networkd to send hostname in DHCP requests
    systemd.network.networks."40-ethernet" = {
      matchConfig.Name = "enp0s10";
      networkConfig = {
        DHCP = "yes";
        IPv6PrivacyExtensions = "kernel";
      };
      dhcpV4Config = {
        SendHostname = true;
        Hostname = "mbp";
      };
    };

    # Console configuration (Solarized Dark theme)
    console = {
      packages = [ pkgs.kbd pkgs.terminus_font pkgs.powerline-fonts ];
      font = "${pkgs.powerline-fonts}/share/consolefonts/ter-powerline-v20b.psf.gz";
      keyMap = "us";
      colors = [
        "002b36" # base03, background
        "dc322f" # red
        "859900" # green
        "b58900" # yellow
        "268bd2" # blue
        "d33682" # magenta
        "2aa198" # cyan
        "eee8d5" # base2, foreground
        "073642" # base02, bright background
        "cb4b16" # bright red
        "586e75" # base01, bright green
        "657b83" # base00, bright yellow
        "839496" # base0, bright blue
        "6c71c4" # violet, bright magenta
        "93a1a1" # base1, bright cyan
        "fdf6e3" # base3, bright foreground
      ];
    };

    # User configuration - mostly handled by system-default layer
    # This adds host-specific package (home-manager)
    users.users.${username}.packages = lib.mkDefault (with pkgs; [
      inputs.home-manager.packages.${pkgs.stdenv.hostPlatform.system}.default
    ]);

    # Enable GnuPG agent with SSH support
    programs.gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
    };

    # Zsh configuration (system-wide settings for all users)
    programs.zsh = {
      enable = true;
      syntaxHighlighting.enable = true;
      enableCompletion = true;
      enableBashCompletion = true;
      enableGlobalCompInit = true;
      enableLsColors = true;
      setOptions = [
        "EXTENDED_HISTORY"
        "HIST_IGNORE_DUPS"
        "SHARE_HISTORY"
        "HIST_FCNTL_LOCK"
      ];
      interactiveShellInit = ''
        bindkey -v
        bindkey '^R' history-incremental-search-backward
      '';
      promptInit = ''
        autoload -U promptinit
        promptinit
        prompt suse
        setopt prompt_sp
        setopt prompt_subst
        autoload -Uz vcs_info
        precmd () { vcs_info }
        zstyle ':vcs_info:*' formats ' %s(%F{red}%b%f)'
        PS1='%n@%m %F{red}%/%f$vcs_info_msg_0_ $ '
      '';
      histSize = 10000;
    };

    # Additional system packages
    environment = {
      systemPackages = with pkgs; [
        kbd
        terminus_font
        powerline-fonts
      ];
      variables = {
        EDITOR = "nvim";
      };
    };

    # SSH service - override system-cli defaults for this host
    services.openssh.settings.PasswordAuthentication = lib.mkForce true;

    # Disable X server and related services (headless server config)
    services.xserver.enable = false;
    services.printing.enable = false;
    services.pipewire = {
      enable = false;
      pulse.enable = false;
    };

    # Enable touchpad support for MacBook trackpad
    services.libinput.enable = true;

    # Memory management optimizations
    boot.kernel.sysctl."vm.swappiness" = 10;
    zramSwap = {
      enable = true;
      memoryPercent = 25;
    };

    # System state version
    system.stateVersion = "24.11";

    # User environment managed by standalone Home Manager
    # Deploy with: home-manager switch --flake '.#tim@mbp'
  };

  # === Home Manager Module ===
  flake.modules.homeManager."tim@mbp" = { config, lib, pkgs, ... }: {
    imports = [
      # Dendritic system type - provides home-default layer (includes home-minimal)
      inputs.self.modules.homeManager.home-default
      # Files module (scripts, utilities, completions)
      inputs.self.modules.homeManager.files
      # Dendritic feature modules
      inputs.self.modules.homeManager.shell
      inputs.self.modules.homeManager.git
      inputs.self.modules.homeManager.tmux
      inputs.self.modules.homeManager.neovim
      inputs.self.modules.homeManager.claude-code
      inputs.self.modules.homeManager.opencode
      inputs.self.modules.homeManager.secrets-management
      inputs.self.modules.homeManager.github-auth
      inputs.self.modules.homeManager.development-tools
      inputs.self.modules.homeManager.yazi
      inputs.self.modules.homeManager.shell-utils
      inputs.self.modules.homeManager.terminal
      inputs.self.modules.homeManager.system-tools
      inputs.self.modules.homeManager.podman
      inputs.self.modules.homeManager.git-auth-helpers
      # Note: NO wsl-home, esp-idf, onedrive, or windows-terminal - this is bare-metal NixOS, not WSL
    ];

    # Dendritic home-minimal options (required by system types)
    homeMinimal = {
      inherit username homeDirectory;
    };

    # Unified files module (scripts, utilities)
    homeFiles.enable = true;

    # Enable tmux auto-reload on home-manager generation change
    programs.tmux.autoReload.enable = true;

    # Container tools (podman-tui, podman-compose)
    # Aliases default to docker→podman on Linux (platform-aware module)
    programs.podman-tools = {
      enable = true;
      enableCompose = true;
    };

    # Secrets management (dendritic module)
    secretsManagement = {
      enable = true;
      rbw.email = "timblaktu@gmail.com";
    };

    # GitHub authentication (dendritic module)
    gitAuth.github = {
      enable = true;
      mode = "bitwarden";
      bitwarden = {
        item = "github.com";
        field = "PAT-timtam2026";
      };
      cli.tokenOverrides.pr = {
        item = "github.com";
        field = "PAT-pubclassic";
      };
    };

    # Claude Code configuration (using lib presets)
    programs.claude-code = inputs.self.lib.claudeCode.baseConfig // {
      accounts = inputs.self.lib.claudeCode.personalAccounts;
      statusline = inputs.self.lib.claudeCode.defaultStatusline;
      mcpServers = inputs.self.lib.claudeCode.defaultMcpServers;
      subAgents.custom = inputs.self.lib.claudeCode.defaultSubAgents;
    };

    # OpenCode configuration (using lib presets)
    programs.opencode = inputs.self.lib.openCode.baseConfig // {
      accounts = inputs.self.lib.openCode.personalAccounts;
      mcpServers = inputs.self.lib.openCode.defaultMcpServers;
      commands = inputs.self.lib.openCode.defaultCommands;
    };
  };

  # === Configuration Registration ===
  # Note: Registration is done in flake-modules/ files.
  # The host module only defines flake.modules.{nixos,homeManager}.* content.
  # This avoids circular dependencies that occur when trying to both define
  # and register configurations in the same module.
  #
  # Registration happens in:
  # - flake-modules/nixos-configurations.nix
  # - flake-modules/home-configurations.nix
}
