# modules/hosts/thinky-nixos/thinky-nixos.nix
# Dendritic host composition for thinky-nixos (WSL primary development)
#
# This module defines both NixOS system and Home Manager configurations
# following the dendritic pattern. It registers both configurations
# using the flake.lib helpers.
#
# Deploy NixOS: sudo nixos-rebuild switch --flake '.#thinky-nixos'
# Deploy HM:    home-manager switch --flake '.#tim@thinky-nixos'
{ config, lib, inputs, ... }:
let
  # SSH public keys (shared across configurations)
  sshKeys = {
    timblaktu = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkVsx3oZrqwkfU6FmhqNEeAGN8dj6lPxNcEwVCmJcQh timblaktu@gmail.com";
    termux = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD0DXHenlcf0zlOqFqc67Ktbk7kbx60RMn+6kZQtBjW1MnDwOf+5JDxTYvlxsAYpWubBxhWopfAEUds7LgB7QCMqbTr6Nco0OAhJGmaDIAP9cFBd8eqTo2oIDelD8jbakNevxIgSbA/nD0wNtVzW+fYtCF32kIs9SbUaO5fLet7dc76hUpi2G/Vuq8fE5wjHQiSkGfJlXusaeE/M9N5uYMssdG9dGgZqrZrA1A4REifOGZb5Db2OgBhESVyuxwF6AMpeXLFpYFPCazuSOXLDWoDfmgtrvQPvnyLRR5wC4/WmciURvlNHEhQNPrRC+oukxN1PB7+SXtHolFiHccNZc3n/C63kcJQulA5dXPH08+6tCu7CPaG5u02tth1iIYXByiTzaEGpgnMU2OZllAuVq+rGYSDvnyEuFDmQOn/aDfGt/Cky3w6udfRWIlG9h/yjvOItaQtELc81bKrWE5WnAEwbglpwQ0jzNmnzk08F34R+rcBqz0ZH8yh4pcLE2CIGHM= u0_a695@localhost";
  };

  # Common user settings
  username = "tim";
  homeDirectory = "/home/${username}";
in
{
  # === NixOS System Module ===
  flake.modules.nixos.thinky-nixos = { config, lib, pkgs, ... }: {
    imports = [
      # Hardware configuration (generated by nixos-generate-config)
      ./_hardware-config.nix
      # Dendritic system type - provides system-cli layer (includes default and minimal)
      inputs.self.modules.nixos.system-cli
      # Dendritic WSL configuration
      inputs.self.modules.nixos.wsl
    ];

    # System default layer configuration (required by system types)
    systemDefault.userName = username;

    # WSL settings (dendritic module)
    wsl-settings = {
      hostname = "thinky-nixos";
      defaultUser = username;
      sshPort = 2223;
      userGroups = [ "wheel" "dialout" ];
      sshAuthorizedKeys = [ sshKeys.timblaktu sshKeys.termux ];
      usbip.autoAttach = [ "3-1" "3-2" ];
      # Enable QEMU user-mode emulation for cross-arch builds (aarch64)
      binfmt.enable = true;
      extraShellAliases = {
        esp32c5 = "esp-idf-shell";
      };
    };

    # USB device management for ESP32 development
    services.udev.packages = [
      (pkgs.writeTextFile {
        name = "10-esp32-usb";
        destination = "/etc/udev/rules.d/10-esp32-usb.rules";
        text = ''
          # CP2102N USB to UART Bridge Controller - Device 1
          # Serial: a84d26d0ef5fef1186befc45d9b539e6
          SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="a84d26d0ef5fef1186befc45d9b539e6", SYMLINK+="ttyESP0", MODE="0666", GROUP="dialout"

          # CP2102N USB to UART Bridge Controller - Device 2
          # Serial: 4095a7a28d1af0119da88250ac170b28
          SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="4095a7a28d1af0119da88250ac170b28", SYMLINK+="ttyESP1", MODE="0666", GROUP="dialout"

          # Generic rule for all CP2102N devices (fallback)
          # This ensures any CP2102N device gets proper permissions even if not explicitly listed
          SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666", GROUP="dialout"

          # Also handle the usb-serial subsystem
          SUBSYSTEM=="usb-serial", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE="0666", GROUP="dialout"
        '';
      })
    ];

    # User environment managed by standalone Home Manager
    # Deploy with: home-manager switch --flake '.#tim@thinky-nixos'
  };

  # === Home Manager Module ===
  flake.modules.homeManager."tim@thinky-nixos" = { config, lib, pkgs, ... }: {
    imports = [
      # Dendritic system type - provides home-default layer (includes home-minimal)
      inputs.self.modules.homeManager.home-default
      # Files module (scripts, utilities, completions)
      inputs.self.modules.homeManager.files
      # Dendritic feature modules
      inputs.self.modules.homeManager.shell
      inputs.self.modules.homeManager.git
      inputs.self.modules.homeManager.tmux
      inputs.self.modules.homeManager.neovim
      inputs.self.modules.homeManager.wsl-home
      inputs.self.modules.homeManager.claude-code
      inputs.self.modules.homeManager.opencode
      inputs.self.modules.homeManager.secrets-management
      inputs.self.modules.homeManager.github-auth
      inputs.self.modules.homeManager.development-tools
      inputs.self.modules.homeManager.yazi
      inputs.self.modules.homeManager.shell-utils
      inputs.self.modules.homeManager.terminal
      inputs.self.modules.homeManager.system-tools
      inputs.self.modules.homeManager.esp-idf
      inputs.self.modules.homeManager.onedrive
      inputs.self.modules.homeManager.podman
      inputs.self.modules.homeManager.windows-terminal
      inputs.self.modules.homeManager.git-auth-helpers
    ];

    # Dendritic home-minimal options (required by system types)
    homeMinimal = {
      inherit username homeDirectory;
    };

    # WSL home settings (dendritic module)
    wsl-home-settings = {
      distroName = "nixos";
    };

    # ESP-IDF development environment (WSL host)
    espIdf.enable = true;

    # OneDrive utilities (WSL host)
    oneDriveUtils.enable = true;

    # Unified files module (scripts, utilities)
    homeFiles.enable = true;

    # Container tools (podman-tui, podman-compose)
    programs.podman-tools = {
      enable = true;
      enableCompose = true;
      aliases = {
        docker = "podman";
        d = "podman";
        dc = "podman-compose";
      };
    };

    # Enable tmux auto-reload on home-manager generation change
    programs.tmux.autoReload.enable = true;

    # Secrets management (dendritic module)
    secretsManagement = {
      enable = true;
      rbw.email = "timblaktu@gmail.com";
    };

    # GitHub authentication (dendritic module)
    gitAuth.github = {
      enable = true;
      mode = "bitwarden";
      bitwarden = {
        item = "github.com";
        field = "PAT-timtam2026";
      };
      cli.tokenOverrides.pr = {
        item = "github.com";
        field = "PAT-pubclassic";
      };
    };

    # Claude Code configuration (using lib presets)
    programs.claude-code = inputs.self.lib.claudeCode.baseConfig // {
      accounts = inputs.self.lib.claudeCode.personalAccounts;
      statusline = inputs.self.lib.claudeCode.defaultStatusline;
      mcpServers = inputs.self.lib.claudeCode.defaultMcpServers;
      subAgents.custom = inputs.self.lib.claudeCode.defaultSubAgents;
    };

    # OpenCode configuration (using lib presets)
    programs.opencode = inputs.self.lib.openCode.baseConfig // {
      accounts = inputs.self.lib.openCode.personalAccounts;
      mcpServers = inputs.self.lib.openCode.defaultMcpServers;
      commands = inputs.self.lib.openCode.defaultCommands;
    };
  };

  # === Configuration Registration ===
  # Note: Registration is done in flake-modules/ files using lib helpers.
  # The host module only defines flake.modules.{nixos,homeManager}.* content.
  # This avoids circular dependencies that occur when trying to both define
  # and register configurations in the same module.
  #
  # Registration happens in:
  # - flake-modules/nixos-configurations.nix (uses lib.mkNixos)
  # - flake-modules/home-configurations.nix (uses lib.mkHomeManager)
}
